Create view Nombre_de_cartes_par_joueur as(
  Select JOUEURS.ID_JOUEUR, JOUEURS.NOM_JOUEUR, JOUEURS.PRENOM_JOUEUR,
  JOUEURS.PSEUDONYME_JOUEUR, count(POSSESSIONS_EXEMPLAIRES.ID_EXEMPLAIRE)
  from POSSESSIONS_EXEMPLAIRES
  INNER JOIN JOUEURS on JOUEURS.ID_JOUEUR = POSSESSIONS_EXEMPLAIRES.ID_JOUEUR
  group by POSSESSIONS_EXEMPLAIRES.ID_JOUEUR);

Create view classement_joueurs as(
  Select JOUEURS.*
  sum((EXEMPLAIRES.QUALITE/100)*APPARTENANCES.COTE) as VALEUR
  from JOUEURS
  natural join EXEMPLAIRES
  natural join APPARTENANCES
  group by ID_JOUEUR
  order by VALEUR
)
