Select JOUEURS.NOM_JOUEUR, count(JOUEURS.NOM_JOUEUR) AS NB_RARE from (JOUEURS
join POSSESSIONS_EXEMPLAIRES on POSSESSIONS_EXEMPLAIRES.ID_JOUEUR = JOUEURS.ID_JOUEUR)
join EXEMPLAIRES on EXEMPLAIRES.ID_EXEMPLAIRE = POSSESSIONS_EXEMPLAIRES.ID_EXEMPLAIRE
where EXEMPLAIRES.ID_CARTE in
(Select CARTES.ID_CARTE from CARTES
  join APPARTENANCES on APPARTENANCES.ID_CARTE = CARTES.ID_CARTE
  where APPARTENANCES.NB_TIRAGE <= 100) OR EXEMPLAIRES.DATE_IMPRESSION <= '01-JAN-2000'
group by JOUEURS.NOM_JOUEUR
order by NB_RARE DESC
;
